version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_web_app
    ports:
      - "5000:5000"  
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_ENV: development
    command: python app.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia 
